title: CloBiz - Simone Russo
github_url: https://github.com/TheTuxNet
linkedin_url: https://www.linkedin.com/in/simonerusso/
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:  Code snippets & notes
theme: jekyll-theme-hacker
google_analytics: UA-48150112-4 # your Google Analytics tracking ID here
author: Simone Russo
paginate: 4
# paginate_path: /page/:num/

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap